export const ARI_URL = 'ARI_URL';
export const ARI_USERNAME = 'ARI_USERNAME';
export const ARI_PASSWORD = 'ARI_PASSWORD';
export const ARI_APPLICATION_NAME = 'ARI_APPLICATION_NAME';
export const SAT_URL = 'SAT_URL';
export const AUDIO_URL = 'AUDIO_URL';
export const CLIENT_ID = 'CLIENT_ID';
export const CLIENT_SECRET = 'CLIENT_SECRET';
export const USUARIO = 'USUARIO';
export const CLAVE = 'CLAVE';
export const REALM = 'REALM';
export const GRANT_TYPE = 'GRANT_TYPE';



// ASTERISK RECORDINGS ===
export const ASTERISK_RECORDINGS_URL = 'ASTERISK_RECORDINGS_URL';
export const ASTERISK_UPLOAD_URL = 'ASTERISK_UPLOAD_URL';
export const ASTERISK_RECORDINGS_FORMAT = 'ASTERISK_RECORDINGS_FORMAT';

// ARCHIVOS TEMPORALES ===
export const TEMP_AUDIO_DIR = 'TEMP_AUDIO_DIR';
export const TEMP_FILE_CLEANUP_TIMEOUT = 'TEMP_FILE_CLEANUP_TIMEOUT';

// CONFIGURACIÓN DE GRABACIÓN ===
export const RECORDING_MAX_DURATION = 'RECORDING_MAX_DURATION';
export const RECORDING_MAX_SILENCE = 'RECORDING_MAX_SILENCE';
export const RECORDING_FORMAT = 'RECORDING_FORMAT';
export const RECORDING_BEEP_ENABLED = 'RECORDING_BEEP_ENABLED';
export const RECORDING_IF_EXISTS = 'RECORDING_IF_EXISTS';

// TIMEOUTS Y DELAYS ===
export const IVR_FILE_WRITE_DELAY = 'IVR_FILE_WRITE_DELAY';
export const IVR_PLAYBACK_TIMEOUT = 'IVR_PLAYBACK_TIMEOUT';
export const IVR_SESSION_CLEANUP_INTERVAL = 'IVR_SESSION_CLEANUP_INTERVAL';
export const IVR_SESSION_EXPIRY_TIME = 'IVR_SESSION_EXPIRY_TIME';
export const IVR_WEBSOCKET_RECONNECT_DELAY = 'IVR_WEBSOCKET_RECONNECT_DELAY';